version: "3.8"

services:
  app:
    ports:
      - "48000:8000"
    command: /start.sh

    user: "${UID-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    ports:
      - "45432:5432"
