# Generated by Django 5.0.6 on 2024-05-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_details", "0002_category_subcategory_cardetail_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardetail",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardetail",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
